# Configuración de la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/IER
spring.datasource.username=postgres
spring.datasource.password=jazmin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# Usamos 'none' porque ya creamos las tablas manualmente y no queremos que Spring las altere
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true